### ISSUE TITLE
Document.querySelector(`{#$id}`) does not work

### ISSUE THREAD

**Issue by jacklp** [eddyerburgh/avoriaz-mocha-example#2]
I can get the HTML with wrapper.html() which works great, but part of the code I am testing looks for form validation with Document.querySelector(`{#$id}`) and is throwing errors when mocha runs it.

Is this because Avoriaz does not actually render  the vue components into jsdom document at all?

**Comment by eddyerburgh** [comment]
@jacklp avoriaz does not by default, you can pass the `attachToDocument` option to mount:

```js
mount(Component, {attachToDocument: true})
```

https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/

**Comment by jacklp** [comment]
Ah I see that now, thanks for the quick reply! Was looking for the answer for this for so long.
